fix(htw-293): fix depth issue get globals
TechHoldingLLC/payload-tenancy pull request #13
Opened 2024-10-07 12:39 UTC by vrajpatelTH

## Fix: Resolve null values in relation collections when fetching global data

### Summary :
This PR addresses an issue where relation collections (e.g., `media`) are returning `null` values when fetching global data via GraphQL in **Payload CMS's tenancy system**. The issue seems to stem from global hooks affecting the retrieval of relational data.

### Actual Behaviour  :
- Ensures that relation collection values (such as `media` for `sponsors`) are properly fetched and returned.
  
### Expected Behaviour :
- Relation collection values (e.g., `media`) should no longer return null and should be correctly fetched **when querying global data.**

2024-10-07 16:08 UTC, MihirLathiya510 submitted a review, later dismissed

2024-10-07 17:08 UTC, kapilbarad requested changes
@vrajpatelTH This repo uses Yarn, We can remove package-lock file.

2024-10-08 06:07 UTC, MihirLathiya510 approved these changes

2024-10-08 06:10 UTC, kapilbarad approved these changes

2024-10-08 06:10 UTC, merged