fix: published global version
TechHoldingLLC/payload-tenancy pull request #17
Opened 2024-12-04 16:18 UTC by kapilbarad

2024-12-04 16:20 UTC, akshaykher243 approved these changes, later dismissed

2024-12-04 18:24 UTC, RutuThakkar510 submitted a review, later dismissed

2024-12-05 09:58 UTC, th-harsh requested changes

2024-12-05 09:58 UTC, th-harsh commented on dist/hooks/global.js
> +                    console.log('Fetching published version: ');
remove console

2024-12-08 17:23 UTC, kapilbarad commented on dist/hooks/global.js
> +                    console.log('Fetching published version: ');
Done

2024-12-08 17:24 UTC, th-harsh approved these changes

2024-12-08 17:25 UTC, RutuThakkar510 approved these changes

2024-12-08 17:25 UTC, merged